owner: gnosis
repo: cow-uptime

sites:
  - name: CowSwap
    url: https://cowswap.exchange/

  - name: Explorer
    url: http://explorer.cow.fi

  - name: "CowSwap - Barn"
    url: https://barn.cowswap.exchange/

  - name: "Explorer - Barn"
    url: https://barn.explorer.cow.fi

  - name: "CoW Protocol"
    url: https://cow.fi

  - name: "CoW Protocol - Docs"
    url: https://docs.cow.fi


status-website:
  # cname: status.cow.fi
  baseUrl: /cow_uptime
  logoUrl: https://raw.githubusercontent.com/gnosis/cowswap-uptime/master/assets/CowSwap-logo.svg
  name: Upptime
  introTitle: "Status for CowSwap"
  introMessage: Check the availability for CowSwap.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/gnosis/cowswap