owner: gnosis
repo: cowswap

sites:
  - name: "Barn - CowSwap"
    url: https://barn.cowswap.exchange/

  - name: "CowSwap"
    url: https://cowswap.exchange/


status-website:
  # cname: status.cow.fi
  # baseUrl: /your-repo-name
  logoUrl: https://cowswap.exchange/images/og-meta-cowswap.png?v=1
  name: Upptime
  introTitle: "Status for CowSwap"
  introMessage: Check the availability for CowSwap.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/gnosis/cowswap