owner: gnosis
repo: cowswap

sites:
  - name: CowSwap
    url: https://cowswap.exchange/

  - name: Explorer
    url: http://explorer.cow.fi

  - name: "CowSwap - Barn"
    url: https://barn.cowswap.exchange/

  - name: "Explorer - Barn"
    url: https://barn.explorer.cow.fi

  - name: "CoW Protocol"
    url: https://cow.fi

  - name: "CoW Protocol - Docs"
    url: https://docs.cow.fi

  - name: API
    method: POST
    url: https://api.cow.fi/mainnet/api/v1/quote
    headers: ["Content-Type: application/json"]
    body: |
      {
        "kind": "sell",
        "sellAmountBeforeFee": "10000000000000000000",
        "sellToken": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        "buyToken": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "from": "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B",
        "receiver": "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B",
        "appData": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "validTo": 2524608000,
        "partiallyFillable": false
      }

  - name: "Fake CowSwap"
    url: https://cowswap2.exchange/



status-website:
  # cname: status.cow.fi
  baseUrl: /cow-uptime
  logoUrl: https://raw.githubusercontent.com/gnosis/cowswap-uptime/master/assets/CowSwap-logo.svg
  name: Upptime
  introTitle: "Status for CowSwap"
  introMessage: Check the availability for CowSwap.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/gnosis/cowswap
    - title: Analytics
      href: https://dune.xyz/gnosis.protocol/Gnosis-Protocol-V2
  assignees:
    - alfetopito
    - anxolin
    - W3stside
    - nenadV91
    - biocom
  theme: dark
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"

